### ISSUE TITLE
WavPack support?

### ISSUE THREAD

**Issue by starchivore** [Quake4/SOV.NAudio#2]
Good Day,

First of all, many thanks for creating this lightweight application.

Just a quick question about WavPack support, is it OK to take a look at this?

[https://github.com/koobar/NAudio.WavPack](https://github.com/koobar/NAudio.WavPack)
>In addition to this library, you will need `wavpackdll.dll` that is compatible with the platform of your execution environment. Please obtain it separately from the WavPack author's page.

The latest version is available here:

[https://github.com/dbry/WavPack/releases/download/5.7.0/wavpack-5.7.0-dll.zip](https://github.com/dbry/WavPack/releases/download/5.7.0/wavpack-5.7.0-dll.zip)

I hope that adding support for WavPack wouldn't be all that challenging at all, thank you very much and have a great weekend.

**Comment by Quake4** [comment]
Ok. I'll take a look.

**Comment by Quake4** [comment]
Added. So far without TAG support.

**Comment by Quake4** [comment]
added tags and cue in tags support
